project_id: "perfume-marketplace"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /messages/en.json
    translation: /messages/%two_letters_code%.json
    
  - source: /app/[locale]/about/en.mdx
    translation: /app/[locale]/about/%two_letters_code%.mdx

  - source: /public/locales/en/**/*.json
    translation: /public/locales/%two_letters_code%/**/%original_file_name%

