import { Perfume, Review } from '@/types/perfume'

export const mockPerfumes: Perfume[] = [
  {
    id: '1',
    name: 'Chanel No. 5',
    brand: 'Chanel',
    image: '/chanel-no5.png',
    description: 'A classic floral aldehyde fragrance that has endured as an icon in the world of perfumery.',
    notes: ['aldehydes', 'jasmine', 'rose', 'ylang-ylang', 'sandalwood'],
    rating: 4.5,
    price: 135,
    longevity: 'Long-lasting (6-8 hours)',
    sillage: 'Moderate to strong',
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        username: 'FragranceLover',
        rating: 5,
        comment: 'An absolute classic that never goes out of style.',
        date: '2023-05-15'
      },
      {
        id: 'r2',
        userId: 'u2',
        username: 'ScentExplorer',
        rating: 4,
        comment: 'Sophisticated and timeless, but may not be for everyone.',
        date: '2023-06-02'
      }
    ]
  },
  {
    id: '2',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    image: '/bleu-de-chanel.png',
    description: 'A woody aromatic fragrance for men that exudes sophistication and modernity.',
    notes: ['incense', 'ginger', 'sandalwood', 'citrus', 'labdanum'],
    rating: 4.7,
    price: 122,
    longevity: 'Very long-lasting (8-10 hours)',
    sillage: 'Moderate',
    reviews: [
      {
        id: 'r3',
        userId: 'u3',
        username: 'CologneCritic',
        rating: 5,
        comment: 'My go-to fragrance for any occasion. Versatile and long-lasting.',
        date: '2023-05-20'
      },
      {
        id: 'r4',
        userId: 'u4',
        username: 'FragranceNewbie',
        rating: 4,
        comment: 'Smells great but a bit pricey for my budget.',
        date: '2023-06-10'
      }
    ]
  },
  {
    id: '3',
    name: 'Black Orchid',
    brand: 'Tom Ford',
    image: '/black-orchid.png',
    description: 'A captivating oriental floral fragrance with dark and mysterious notes.',
    notes: ['black truffle', 'ylang-ylang', 'black currant', 'patchouli'],
    rating: 4.6,
    price: 134,
    longevity: 'Very long lasting',
    sillage: 'Strong',
    reviews: [],
  },
  {
    id: '4',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    image: '/la-vie-est-belle.png',
    description: 'A gourmand floral fragrance that is both sweet and sophisticated.',
    notes: ['iris', 'patchouli', 'praline', 'vanilla'],
    rating: 4.7,
    price: 100,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '5',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    image: '/bleu-de-chanel.png',
    description: 'A woody aromatic fragrance for men that exudes sophistication and modernity.',
    notes: ['incense', 'ginger', 'sandalwood', 'citrus'],
    rating: 4.6,
    price: 122,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '6',
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    image: '/light-blue.png',
    description: 'A refreshing and vibrant citrus aromatic fragrance for women.',
    notes: ['lemon', 'apple', 'cedar', 'bellflower'],
    rating: 4.4,
    price: 76,
    longevity: 'Moderate',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '7',
    name: 'Tobacco Vanille',
    brand: 'Tom Ford',
    image: '/tobacco-vanille.png',
    description: 'A warm and inviting oriental fragrance with notes of tobacco and vanilla.',
    notes: ['tobacco leaf', 'vanilla', 'cocoa', 'tonka bean'],
    rating: 4.7,
    price: 240,
    longevity: 'Very long lasting',
    sillage: 'Strong',
    reviews: [],
  },
  {
    id: '8',
    name: 'J\'adore',
    brand: 'Dior',
    image: '/jadore.png',
    description: 'A floral fragrance that is both elegant and sensual.',
    notes: ['ylang-ylang', 'damascus rose', 'jasmine', 'tuberose'],
    rating: 4.5,
    price: 135,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '9',
    name: 'Acqua di Gio',
    brand: 'Giorgio Armani',
    image: '/acqua-di-gio.png',
    description: 'A fresh and invigorating aquatic fragrance for men.',
    notes: ['marine notes', 'bergamot', 'neroli', 'jasmine'],
    rating: 4.6,
    price: 90,
    longevity: 'Moderate',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '10',
    name: 'Flowerbomb',
    brand: 'Viktor&Rolf',
    image: '/flowerbomb.png',
    description: 'A powerful and captivating floral fragrance with a sweet and intoxicating aroma.',
    notes: ['tea', 'bergamot', 'sambac jasmine', 'orange blossom', 'patchouli'],
    rating: 4.5,
    price: 165,
    longevity: 'Long lasting',
    sillage: 'Strong',
    reviews: [],
  },
  {
    id: '11',
    name: 'Eros',
    brand: 'Versace',
    image: '/eros.png',
    description: 'A fresh and sensual fragrance for men with a blend of aromatic and woody notes.',
    notes: ['mint', 'green apple', 'vanilla', 'ambroxan'],
    rating: 4.4,
    price: 88,
    longevity: 'Long lasting',
    sillage: 'Strong',
    reviews: [],
  },
  {
    id: '12',
    name: 'Alien',
    brand: 'Mugler',
    image: '/alien.png',
    description: 'A captivating and mysterious floral woody amber fragrance for women.',
    notes: ['jasmine sambac', 'cashmeran', 'amber', 'white amber'],
    rating: 4.5,
    price: 115,
    longevity: 'Very long lasting',
    sillage: 'Very strong',
    reviews: [],
  },
  {
    id: '13',
    name: 'Terre d\'Hermès',
    brand: 'Hermès',
    image: '/terre-dhermes.png',
    description: 'A sophisticated and earthy fragrance for men with a blend of woody and citrus notes.',
    notes: ['orange', 'pepper', 'vetiver', 'cedar'],
    rating: 4.5,
    price: 126,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '14',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    image: '/black-opium.png',
    description: 'A captivating and seductive oriental vanilla fragrance for women.',
    notes: ['coffee', 'vanilla', 'white flowers', 'cedar'],
    rating: 4.6,
    price: 124,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  },
  {
    id: '15',
    name: 'Oud Wood',
    brand: 'Tom Ford',
    image: '/oud-wood.png',
    description: 'A rich and luxurious woody fragrance with notes of oud, rosewood, and cardamom.',
    notes: ['oud', 'rosewood', 'cardamom', 'sandalwood'],
    rating: 4.6,
    price: 250,
    longevity: 'Long lasting',
    sillage: 'Moderate',
    reviews: [],
  }
]

