import { PerfumeData } from '@/types/perfume'

export const perfumes: PerfumeData[] = [
  {
    id: '1',
    name: 'Chanel No. 5',
    brand: 'Chanel',
    price: 135,
    rating: 4.8,
    image: '/images/chanel-no-5.jpg',
    notes: ['aldehydes', 'jasmine', 'rose'],
    description: 'An iconic fragrance that has endured for decades.',
  },
  {
    id: '2',
    name: 'Dior Sauvage',
    brand: 'Dior',
    price: 95,
    rating: 4.5,
    image: '/images/dior-sauvage.jpg',
    notes: ['bergamot', 'pepper', 'ambroxan'],
    description: 'A fresh and bold scent for the modern man.',
  },
  {
    id: '3',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    price: 125,
    rating: 4.7,
    image: '/images/black-opium.jpg',
    notes: ['coffee', 'vanilla', 'white flowers'],
    description: 'A seductively intoxicating women's fragrance.',
  },
  {
    id: '4',
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    price: 80,
    rating: 4.3,
    image: '/images/light-blue.jpg',
    notes: ['lemon', 'apple', 'cedar'],
    description: 'A refreshing and vibrant scent for summer days.',
  },
  {
    id: '5',
    name: 'Aventus',
    brand: 'Creed',
    price: 325,
    rating: 4.9,
    image: '/images/aventus.jpg',
    notes: ['pineapple', 'birch', 'musk'],
    description: 'A sophisticated and bold fragrance for the confident man.',
  },
  {
    id: '6',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    price: 100,
    rating: 4.6,
    image: '/images/la-vie-est-belle.jpg',
    notes: ['iris', 'patchouli', 'praline'],
    description: 'A sweet and feminine fragrance celebrating the beauty of life.',
  },
  {
    id: '7',
    name: 'Acqua di Gio',
    brand: 'Giorgio Armani',
    price: 90,
    rating: 4.4,
    image: '/images/acqua-di-gio.jpg',
    notes: ['marine notes', 'bergamot', 'neroli'],
    description: 'A timeless aquatic fragrance inspired by the Mediterranean sea.',
  },
  {
    id: '8',
    name: 'Flowerbomb',
    brand: 'Viktor&Rolf',
    price: 115,
    rating: 4.5,
    image: '/images/flowerbomb.jpg',
    notes: ['orchid', 'rose', 'freesia'],
    description: 'An explosive floral bouquet with a sweet and addictive scent.',
  },
  {
    id: '9',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    price: 105,
    rating: 4.7,
    image: '/images/bleu-de-chanel.jpg',
    notes: ['incense', 'ginger', 'sandalwood'],
    description: 'A woody aromatic fragrance for the charismatic modern man.',
  },
  {
    id: '10',
    name: 'J'adore',
    brand: 'Dior',
    price: 110,
    rating: 4.6,
    image: '/images/jadore.jpg',
    notes: ['ylang-ylang', 'damascus rose', 'jasmine'],
    description: 'A luxurious floral bouquet celebrating feminine sensuality.',
  }
]

